import './globals.css'
import { Inter } from 'next/font/google'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo',
}

interface LayoutProps {
	children: React.ReactNode
}

const RootLayout = ({ children }: LayoutProps): JSX.Element => {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	)
}

export default RootLayout
