import './globals.css'
import '@repo/ui/styles.css'
import { Inter } from 'next/font/google'

import Footer from '@/components/layout/Footer'
import Header from '@/components/layout/Header'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

type LayoutProps = Readonly<{
	children: React.ReactNode
}>

const RootLayout = ({ children }: LayoutProps): JSX.Element => (
	<html lang="en" className="scroll-smooth">
		<body className={inter.className}>
			<Header />
			{children}
			<Footer />
		</body>
	</html>
)

export default RootLayout
